plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version "${forge_gradle_version}"
    id 'org.spongepowered.mixin' version "${mixin_gradle_version}"
    id 'com.github.johnrengelman.shadow' version "${shadow_gradle_version}"
}

version = mod_version
group = "com.github.mcjty"
base.archivesName = mod_id

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: mappings_channel, version: mappings_version
}

configurations {
    embed
}

repositories {
    flatDir { dirs 'libs' }
    maven { url = "https://www.cursemaven.com" }
    maven { url = "https://maven.k-4u.nl" }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    shadow "org.spongepowered:mixin:${mixin_version}"
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
    shadow "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"
    annotationProcessor "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"
	
	implementation fg.deobf("com.github.mcjty:mcjtytools:${mcjtytools_version}")
	embed ("com.github.mcjty:mcjtytools:${mcjtytools_version}")
    compileOnly fg.deobf("curse.maven:baubles-${baubles_version}")
    compileOnly fg.deobf("curse.maven:jei-${jei_version}")
    compileOnly fg.deobf("curse.maven:lostcities-${lostcities_version}")
    compileOnly fg.deobf("curse.maven:gamestages-${gamestages_version}")
    compileOnly fg.deobf("curse.maven:sereneseasons-${sereneseasons_version}")
}

mixin {
    add sourceSets.main, "mixins.${mod_id}.refmap.json"
}

processResources {
    var replaceProperties = [
            'mod_id': mod_id,
            'mod_name': mod_name,
            'version': mod_version,
            'mcversion': minecraft_version,
            'mod_description': mod_description,
            'mod_author': mod_author
    ]

    inputs.properties replaceProperties

    filesMatching('mcmod.info') {
        expand replaceProperties
    }
}

//Gross but shadow is annoying
tasks.register('mergeJar', Jar) {
    from configurations.embed
    destinationDirectory = file 'build/temp'
    archiveBaseName = 'temp'
}

shadowJar {
    dependsOn mergeJar

    configurations = [project.configurations.shadow]
    mergeServiceFiles()

    exclude 'org/spongepowered/asm/launch/MixinLaunchPlugin*'
    exclude 'org/spongepowered/asm/launch/MixinTransformationService*'
    exclude 'org/spongepowered/asm/launch/platform/container/ContainerHandleModLauncherEx*'

    archiveClassifier.set('')

    from mergeJar {
        into '/META-INF/libraries'
    }
    exclude 'META-INF/libraries/META-INF', 'META-INF/libraries/META-INF/**'
}

reobf {
    shadowJar {}
}

jar {
    manifest {
        attributes([
                'Specification-Title'     : mod_name,
                'Specification-Vendor'    : mod_author,
                'Specification-Version'   : '1',
                'Implementation-Title'    : mod_name,
                'Implementation-Vendor'   : mod_author,
                'Implementation-Version'  : mod_version,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'FMLCorePlugin': mixin_loader_class,
                'FMLCorePluginContainsFMLMod': 'true',
                'ForceLoadAsMod': 'true',
                'TweakClass': 'org.spongepowered.asm.launch.MixinTweaker'
        ])
    }

    doFirst {
        manifest {
            def contained = configurations.embed.collect { it.getName() };
            if (!contained.isEmpty()) {
                attributes([
                        "ContainedDeps": contained.join(' ')
                ])
            }
        }
    }
	
    archiveClassifier.set('THIN')

    into('/META-INF/libraries') {
        from configurations.embed
    }
}

build.dependsOn(shadowJar)
jar.finalizedBy('reobfJar')