# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12

# mixin
mixin_gradle_version=0.7.+
mixin_version=0.8.5

shadow_gradle_version=8.1.1

# mod
mod_id=incontrol
mod_name=InControl
mod_version=1.12-3.9.18
mod_author=["McJty (Original)", "fonnymunkey (Fork)"]
mod_description=Be In Control
mixin_loader_class=mcjty.incontrol.InControlPlugin

mcjtytools_version=1.12-0.0.21
baubles_version=227083:2518667
jei_version=238222:5846804
lostcities_version=269024:2861574
gamestages_version=268655:2951840
sereneseasons_version=291874:2799213